In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [19]:
# separate columns by ;
df = pd.read_csv('../atis_dataset.csv', sep=';')

In [20]:
df.head()

,airport_icao,visibility,wind_speed,wind_direction,rvr,runway_designator_number,runway_designator_side,runway_ils_category,headwind,crosswind,ceiling,weather_phenomenon,ILS,RNAV,RNP,VISUAL
0,KIAD,10.0,6,180,>6000,19,L,CAT III,5.9,1.0,0.0,NaN,1,0,0,1
1,KIAD,10.0,6,180,>6000,19,C,CAT III,5.9,1.0,0.0,NaN,1,0,0,1
2,KIAD,10.0,6,180,>6000,19,R,CAT III,5.9,1.0,0.0,NaN,1,0,0,1
3,KLAX,10.0,4,40,>6000,6,R,No ILS,3.8,1.4,0.0,NaN,0,1,1,0
4,KSFO,10.0,8,260,>6000,28,L,CAT III,7.5,2.7,0.0,NaN,1,0,0,0

In [21]:
df.iloc[22]

airport_icao                  KATL
visibility                    10.0
wind_speed                       3
wind_direction                 240
rvr                         >6000
runway_designator_number        28
runway_designator_side         NaN
runway_ils_category         No ILS
headwind                       2.3
crosswind                      1.9
ceiling                        0.0
weather_phenomenon             NaN
ILS                              0
RNAV                             0
RNP                              0
VISUAL                           1
Name: 22, dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6520 entries, 0 to 6519
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   airport_icao              6520 non-null   object
 1   visibility                6520 non-null   float64
 2   wind_speed                6520 non-null   int64
 3   wind_direction            6520 non-null   int64
 4   rvr                       6520 non-null   object
 5   runway_designator_number  6520 non-null   int64
 6   runway_designator_side    5958 non-null   object
 7   runway_ils_category       6520 non-null   object
 8   headwind                  6520 non-null   float64
 9   crosswind                 6520 non-null   float64
 10  ceiling                   6516 non-null   float64
 11  weather_phenomenon        583 non-null    object
 12  ILS                       6520 non-null   int64
 13  RNAV                      6520 non-null   int64
 14  RNP                       6520 non-null   int64
 15  VISUAL                    6520 non-null   int64
dtypes: float64(4), int64(7), object(5)
memory usage: 815.1+ KB

In [23]:
# check null values before preprocess
df.isnull().sum()

airport_icao                   0
visibility                     0
wind_speed                     0
wind_direction                 0
rvr                            0
runway_designator_number       0
runway_designator_side       562
runway_ils_category            0
headwind                       0
crosswind                      0
ceiling                        4
weather_phenomenon          5937
ILS                            0
RNAV                           0
RNP                            0
VISUAL                         0
dtype: int64

In [24]:
# delete rows where rvr = FFF
df = df[df['rvr'] != 'FFF']

In [25]:
# change N/A weather_phenomenon to "None"
df['weather_phenomenon'] = df['weather_phenomenon'].fillna('None')

In [26]:
# fill empty runway_designator_side to X
df['runway_designator_side'] = df['runway_designator_side'].fillna('X') # X means no L, R, or C

In [27]:
# check after preprocessed
df.head()

,airport_icao,visibility,wind_speed,wind_direction,rvr,runway_designator_number,runway_designator_side,runway_ils_category,headwind,crosswind,ceiling,weather_phenomenon,ILS,RNAV,RNP,VISUAL
0,KIAD,10.0,6,180,>6000,19,L,CAT III,5.9,1.0,0.0,None,1,0,0,1
1,KIAD,10.0,6,180,>6000,19,C,CAT III,5.9,1.0,0.0,None,1,0,0,1
2,KIAD,10.0,6,180,>6000,19,R,CAT III,5.9,1.0,0.0,None,1,0,0,1
3,KLAX,10.0,4,40,>6000,6,R,No ILS,3.8,1.4,0.0,None,0,1,1,0
4,KSFO,10.0,8,260,>6000,28,L,CAT III,7.5,2.7,0.0,None,1,0,0,0

In [28]:
df.iloc[22]

airport_icao                  KATL
visibility                    10.0
wind_speed                       3
wind_direction                 240
rvr                         >6000
runway_designator_number        28
runway_designator_side           X
runway_ils_category         No ILS
headwind                       2.3
crosswind                      1.9
ceiling                        0.0
weather_phenomenon            None
ILS                              0
RNAV                             0
RNP                              0
VISUAL                           1
Name: 22, dtype: object

In [29]:
# check null values after preprocessed
df.isnull().sum()

airport_icao                0
visibility                  0
wind_speed                  0
wind_direction              0
rvr                         0
runway_designator_number    0
runway_designator_side      0
runway_ils_category         0
headwind                    0
crosswind                   0
ceiling                     4
weather_phenomenon          0
ILS                         0
RNAV                        0
RNP                         0
VISUAL                      0
dtype: int64

In [31]:
df.describe()

,visibility,wind_speed,wind_direction,runway_designator_number,headwind,crosswind,ceiling,ILS,RNAV,RNP,VISUAL
count,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6496.000000,6500.000000,6500.000000,6500.000000,6500.000000
mean,9.471115,9.691385,207.162769,20.174923,6.501385,5.271062,5638.793103,0.744462,0.109538,0.076462,0.653538
std,1.831697,5.619615,100.114051,9.608958,5.906386,4.512943,8701.722411,0.436197,0.312338,0.265756,0.475879
min,0.250000,0.000000,-1.000000,1.000000,-10.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,5.000000,150.000000,10.000000,2.500000,1.900000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10.000000,9.000000,220.000000,24.000000,6.000000,4.000000,0.000000,1.000000,0.000000,0.000000,1.000000
75%,10.000000,13.000000,290.000000,28.000000,10.000000,7.800000,7500.000000,1.000000,0.000000,0.000000,1.000000
max,10.000000,29.000000,360.000000,31.000000,29.000000,25.600000,30000.000000,1.000000,1.000000,1.000000,1.000000

In [32]:
# Save the cleaned DataFrame
df.to_csv('atis_dataset_preprocessed.csv', sep=';', index=False)